### ISSUE TITLE
Ability to allow other credential sources

### ISSUE THREAD

**Issue by chris-cartwright** [moxiworks-platform/moxiworks-dotnet#50]
Credentials must be accessible via `ConfigurationManager`. We need the ability to specify another source for the credentials.

I think creating an interface similar to the following would work:
`
public interface ICredentials {
    string ToBase64();
}
`

`ContextClient` would then depend on the new interface.

**Comment by ahatch1490** [comment]
Yes an Interface would be best I will try and get that added.

**Comment by ahatch1490** [comment]
Working on that now should be in next release

**Comment by ahatch1490** [comment]
Add new IMoxiWorksCredentials credentials for custom credentials in  1.2.12.

`var service = new CompanyService(new MoxiWorksClient(new MyCustomCredentials()));`
