### ISSUE TITLE
`moxi_works_contact_id` not exposed on `Contact`

### ISSUE THREAD

**Issue by chris-cartwright** [moxiworks-platform/moxiworks-dotnet#51]
Not all contacts have a `partner_contact_id`. `moxi_works_contact_id` should be exposed as an alternative unique identifier.

**Comment by ahatch1490** [comment]
Thanks for the input I'll look into that.

**Comment by ahatch1490** [comment]
you can just use the moxi_works_contact_id instead of partner_contact_id with no issues
`GetContactAsync(string agentId, AgentIdType.AgentUuid,"685c0e09-e408-40dc-b1ed-ed794e250d9b" )`
