### ISSUE TITLE
Outdated Listing endpoint.

### ISSUE THREAD

**Issue by ajwaggoner42** [moxiworks-platform/moxiworks-dotnet#53]
Updating a VirtualTourURL using the Listing endpoint:
PUT: `https://api.moxiworks.com/api/listings/<listingGuid>?VirtualTourURL=<url>`

which works as expected.

Updating a VirtualTourURL using the moxiworks-dotnet package:
 Returns the non-updated object back.

It looks to be an issue serializing the ListingUpdateableObject, which ends up with something like

`listing { VirtualTourUrl: <url>  }`

instead of passing VirtualTourUrl directly.

**Comment by tres** [comment]
Hi, thanks for letting us know about the issue. We'll take a look at things and see if we can't get an update pushed out for you.

**Comment by ahatch1490** [comment]
@tres send me the api changes that need to happen and I can do the update.

**Comment by tres** [comment]
@ajwaggoner42 Can you clarify what you are receiving and what you expect to receive?

A concrete example would be helpful: what you are receiving and what you expect to receive.

This would be helpful  in determining what needs to be modified here. 

Thanks again for letting us know about this issue and your help in getting it resolved.

**Comment by ajwaggoner42** [comment]
Sure. Currently when using the Moxiworks NuGet package, this is how we're updating a virtualTourUrl
```

            var moxiWorksClient = new MoxiWorks.Platform.MoxiWorksClient();
            var moxiWorksApi = new MoxiWorks.Platform.ListingService(moxiWorksClient);

            var update = new MoxiWorks.Platform.ListingUpdate() { Listing = new MoxiWorks.Platform.ListingUpdatableData() };
            update.Listing.VirtualTourURL = "https://my.paradym.com";
            update.MoxiWorksCompanyId = "moxi_works";
            update.MoxWorksListingId = "5ce0e9a5-6015-fec5-aadf-a328b3d28d28";

            var response =  await moxiWorksApi.UpdateListingDataAsync(update);
```
We would expect listing '5ce0e9a5-6015-fec5-aadf-a328b3d28d28' to have an updated VirtualTourURL when we pulled it down again. The return value gives back a List<ListingResults> with the listing unchaged.

Eyeballing it in DotPeek, I think its due to how the VirtualTourURL needs to be sent to the Listings endpoint. I was advised that I should be passing it directly on the PUT request as a URL parameter.
Currently the NuGet package is serializing a ListingUpdateableData object named Listing, which is leading the client make a PUT request with a payload:
```
{  
   "listing":{  
      "VirtualTourURL":"https://my.paradym.com"
   }
}
```

I believe this is making the client return an unchanged listing.

It wasn't working in the .NET NuGet or CURL originally, and then I was told there was a discrepancy in the documentation for the CURL and was advised of the correct CURL. I was able to update that specific listing successfully, but couldn't get a correct result for the NuGet.

**Comment by ahatch1490** [comment]
yeah looking at the api this would be incorrect

**Comment by tres** [comment]
@ahatch1490 I've only updated the structure in order to try fixing this issue; I didn't remove the ListingUpdate object... 

https://github.com/moxiworks-platform/moxiworks-dotnet/pull/54

**Comment by ahatch1490** [comment]
release of 1.2.14 should be out on nuget now. Let me know if there is still an issue.

**Comment by tres** [comment]
thanks, @ahatch1490 !

**Comment by ajwaggoner42** [comment]
Hey all, sorry for testing this so late. I also feel like I might have led you astray, so apologies again.

The CURL version requires the VirtualTourURL directly in the URL, not attached in the payload. Here is a version I wrote up as a workaround:
```
// THIS IS SHADOWING A BASE CLASS FUNCTION
  public new async System.Threading.Tasks.Task<Response<ListingResults>> UpdateListingDataAsync(ListingUpdate listingUpdate) 
        {
            return await Client.PutRequestAsync<ListingResults, ListingUpdate>(new UriBuilder("listings/" + listingUpdate.MoxWorksListingId).AddQueryParameter("moxi_works_company_id", listingUpdate.MoxiWorksCompanyId).AddQueryParameter("VirtualTourURL", listingUpdate.VirtualTourURL).GetUrl(), listingUpdate);
        }
```

I was able to test this against one of my 2 remaining test listings, with success.

**Comment by ahatch1490** [comment]
so it doesn't work in the payload only the url?
looking at the docks i see it shoulkd workin the payload:

https://moxiworks-platform.github.io/#listing-update

**Comment by ajwaggoner42** [comment]
Oddly enough, no. I will say that the documentation seems stale in a few different areas. A while back I had an email exchange with Kylah about the original issue, here's an exerpt:

"Ok, update! Good news….engineering went to fix the bug and the engineer found it was an error in the documentation!
You don't have to wrap the virtual tour attribute in the listing object, as is currently documented
You just pass it as a normal attribute
It should work if you do that! They are going to update the documentation to reflect that in our next release.
Keep me posted if that worked! I believe the specific listing you were trying is what they used to test so you might need to test a new one…or I could go in and try to remove the link. "

Digging through my cURL history, here's an example that failed:

`curl -X PUT \
  https://api.moxiworks.com/api/listings/5ce0e9a5-6015-fec5-aadf-a328b3d28d28 \
  -H 'Accept: application/json' \
  -H 'Authorization: Basic <TOKEN_GOES_HERE>
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: <postman_token>' \
  -H 'cache-control: no-cache' \
  -d '{
  "moxi_works_listing_id":"5ce0e9a5-6015-fec5-aadf-a328b3d28d28",
  "moxi_works_company_id":"moxi_works",
  "VirtualTourURL":"https://my-test-domain.com/path,
}'`

Well, it stilled returns 200 with no errors, but nothing was updated.

Here's an snippet that had worked:

`curl -X PUT \
  'https://api.moxiworks.com/api/listings/5ce0e9a5-6015-fec5-aadf-a328b3d28d28?VirtualTourURL=https://my-test-domain.com/path \
  -H 'Accept: application/json' \
  -H 'Authorization: Basic <Auth_Token_Goes_Here>' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: <Postman_Token>' \
  -H 'cache-control: no-cache' \
  -d '{
  "moxi_works_listing_id":"5ce0e9a5-6015-fec5-aadf-a328b3d28d28",
  "moxi_works_company_id":"moxi_works",
}'`

the previous c# code is in line with how the cURL seems to be working. For now, we'll be using this as a workaround because it is working for our listings.

**Comment by ahatch1490** [comment]
@ajwaggoner42 glad you where able to find a work around.  This appears to be an issue with either the documentation or the the api it self.
@tres will have to look into it see whats what. 

reopening till the actual issue is resolved i.e. code update in the sdk or api change.

**Comment by ahatch1490** [comment]
@tres created link back to this issue on documentation site: https://github.com/moxiworks-platform/moxiworks-platform.github.io/issues/25

**Comment by tres** [comment]
thanks, @ahatch1490 

@ajwaggoner42 , this doesn't seem like a valid request here (the second request which is noted as the working request):

`curl -X PUT \ 'https://api.moxiworks.com/api/listings/5ce0e9a5-6015-fec5-aadf-a328b3d28d28?VirtualTourURL=https://my-test-domain.com/path \ -H 'Accept: application/json' \ -H 'Authorization: Basic <Auth_Token_Goes_Here>' \ -H 'Content-Type: application/json' \ -H 'Postman-Token: <Postman_Token>' \ -H 'cache-control: no-cache' \ -d '{ "moxi_works_listing_id":"5ce0e9a5-6015-fec5-aadf-a328b3d28d28", "moxi_works_company_id":"moxi_works", }'
`

**Comment by ajwaggoner42** [comment]
Sorry, must have been munged when pasting part of it out of Postman
`curl -X PUT 'https://api.moxiworks.com/api/listings/5ce0e9a5-6015-fec5-aadf-a328b3d28d28?VirtualTourURL=https://my-test-url.com&moxi_works_company_id=moxi_works' -H 'Authorization: Basic _INSERT_BASIC_AUTH_TOKEN_' -H 'Accept: application/json' -H 'Content-Type: application/json' 

Here's the more minimal example.

**Comment by tres** [comment]
@ajwaggoner42 thanks for the update.

If you could update this ticket with the request ID returned in the x-request-id header of the response for both a successful and unsuccessful update, it would help a lot. 

I'm seeing 44 requests right now & I'm not seeing any differences in requests. 

Thanks.

**Comment by ajwaggoner42** [comment]
Here's a request id of one I would expect to update: 47247a26-021f-48bf-8c1c-17866aa028a0
Here's a request id of one I would expect to not update: 01267749-4c3e-4c74-bbb2-639cce49b4f6

Now, do you mean successful as in a successful update of VirtualTourURL? Or 200 OK response?

Currently, an issue is when the request is made, the response is still a 200 OK response with the listing coming back in the payload. HOWEVER, it doesn't update the VirtualTourURL. 

Performing it with VirtualTourURL passed in the URL, still nets a 200 OK response, but the object has been updated.

All this being said, once we actually perform an update. It is _not_  updateable anymore. It will also not give an error if it's attempted again .

I'd love to give you an actual test case for pre-bug-fix / post-bug-fix. But We are working with very few updateable listings, and once they are processed, we can no longer use them as an example.

**Comment by tres** [comment]
Here's the params we're getting for the first request (sent with Postman):

```
"47247a26-021f-48bf-8c1c-17866aa028a0" => {
"moxi_works_listing_id"=>"5ce0e9a5-6015-fec5-aadf-a328b3d28d28", "moxi_works_company_id"=>"moxi_works", 
" \"VirtualTourURL\":\"https://moxiworks.com\""=>nil, 
"listing"=>{
"moxi_works_listing_id"=>"5ce0e9a5-6015-fec5-aadf-a328b3d28d28", "moxi_works_company_id"=>"moxi_works"
}
} 

```
It looks like in this case, there's an issue with the JSON which is causing the entirety of the JSON object to be interpreted as the key to a param value. 


And here's the params for the second request (also sent with Postman):

```
"01267749-4c3e-4c74-bbb2-639cce49b4f6" => {
"moxi_works_listing_id"=>"5ce0e9a5-6015-fec5-aadf-a328b3d28d28", 
"moxi_works_company_id"=>"moxi_works", 
"virtual_tour_url"=>"https://moxiworks.com";, 
"listing"=>{
"moxi_works_listing_id"=>"5ce0e9a5-6015-fec5-aadf-a328b3d28d28", 
"moxi_works_company_id"=>"moxi_works", 
"virtual_tour_url"=>"https://moxiworks.com";
}} 

```
In this case, the parameter key "virtual_tour_url" is being passed.  

Here's a different request from you that conforms to the CamelCase VirtualTourUrl parameter (sent with Curl):

```
"a1ef1126-473f-4b50-a2a6-58b94527efdf" => {
"VirtualTourURL"=>"https://my-test-url.com";, 
"moxi_works_company_id"=>"moxi_works", 
"moxi_works_listing_id"=>"5ce0e9a5-6015-fec5-aadf-a328b3d28d28", 
"listing"=>{}} 
```


Finally, here's a request initiated by our QA team to verify the functionality works as advertised: 

```
"24f6142b-4a8b-45f6-9664-6a82fc3e1853" => {
"moxi_works_company_id"=>"moxi_works", 
"VirtualTourURL"=>"https://google.com/13456";,
"moxi_works_listing_id"=>"5ce0e9a5-6015-fec5-aadf-a38675309e9"} 
```

Let me know if these don't help you.

Thanks,
Tres

**Comment by ahatch1490** [comment]
the first one looks like a double serialization

**Comment by ajwaggoner42** [comment]
If you can check the requests when they're used server side, I think getting the request ids from the actual Nuget, run before and after the adjustment would be more helpful.

I was using the curl to figure out why results weren't happening with Moxiworks. I genuinely don't know where virtual_tour_url came from as a parameter.  I couldn't find it when I was looking through my Postman history. I tried quite a few combinations before actually getting an update, by passing it directly in the URL.

I'm lost on how the QA team request showcases correct functionality. I've been having to GET the object before and after to see any changes, because it still returns 200 OK even without updating the VirtualTourUrl.

If anyone can get me a bank of test listings with a blank VirtualTourUrl, I can write up some one time tests to demonstrate it.
